variables:

  TERRAFORM_VERSION: "1.7.1"
  SVC_CONNECTION: "myserviceconnect"
  azuresubscription: "a2b5e6fe-4153-4ca0-a74e-3f5e50da3ac7"
  TERRAFORM_BACKEND_CONTAINER_NAME: "$logs"
  Terraform_backend_storage_name: "testingpipesacc"
  TF_BACKEND_RESOURCE_GROUP_NAME: "testingpipes"
  subscription: "cv_portfolio"
  TF_STATE_NAME: "tfstate"
  environment: "dev"