variables:

  TERRAFORM_VERSION: "1.7.1"
  SVC_CONNECTION: "hellamav"
  azuresubscription: "myserviceconnect"
  TERRAFORM_BACKEND_CONTAINER_NAME: "$logs"
  Terraform_backend_storage_name: "testingpipesacc"
  TF_BACKEND_RESOURCE_GROUP_NAME: "testingpipes"
  subscription: "cv_portfolio"
  TF_STATE_NAME: "tfstate"
  environment: "dev"