variables:

  TERRAFORM_VERSION: "1.7.1"
  SVC_CONNECTION: "myserviceconnect"
  azuresubscription: "a2b5e6fe-4153-4ca0-a74e-3f5e50da3ac7"
  $TF_BACKEND_CONTAINER_NAME: "tfstate"
  $TF_BACKEND_STORAGE_NAME: "testingpipesacc"
  $TF_BACKEND_RESOURCE_GROUP_NAME: "testingpipes"
  subscription: "cv_portfolio"
  $TF_STATE_NAME: "tfstate"
  environment: "dev"
  TENANT_ID: "dcbfd347-01de-412e-81cc-f75a84dbc097"
  $servicePrincipalId: "5c9cdc8e-f993-4ba8-853f-bc1d667938d3"
  $servicePrincipalKey: "owB8Q~G.htu5ZH1KR_D8TvwOW1dEmGaklUjuOb-p"

